config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :admins
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :categories, only: [:show]
  resources :products, only: %i[index show]
  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
    put 'remove_one/:product_id', to: 'carts#removeone', as: :remove_one
  end

  resources :transactions, only: [:new, :create]

  namespace :admin do
    root to: 'products#index'
    resources :products, only: %i[index new create edit update destroy]
    resources :categories, only: %i[index new create edit update destroy]
    resources :orders, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @cart_products_with_qty = current_user.get_cart_products_with_qty
    @cart_total = current_user.cart_total_price
  end

  def add
    current_user.add_to_cart(params[:product_id])
    redirect_to cart_path
  end

  def remove
    current_user.remove_from_cart(params[:product_id])
    redirect_to cart_path
  end

  def removeone
    current_user.remove_one_from_cart(params[:product_id])
    redirect_to cart_path
  end
end

app/views/carts/show.html.erb
<h1 class='jumbotron'>your shopping cart</h1>
<div class='container'>
  <p>price</p>
  <p>Name</p>
  <p>Quantity</p>
  <p>Subtotal</p>
</div>

<% @cart_products_with_qty.each do |array| %>
<% product = array[0]%>
<% qty = array[1]%>

<%= product.name%>
<%= product.price%>
<%= qty %>
<%= product.price*qty.to_i %>
<%= link_to '+', add_to_cart_path(product), method: :put %>
<%= link_to '-', remove_one_cart_path(product), method: :put %>
<%= link_to 'Remove', remove_from_cart_path(product), method: :put %>
<%= link_to 'checkout', new_transaction_path unless current_user.get_cart_products_with_qty.blank?%> 
<p>total</p>
<%= @cart_total %>
<% end %>