config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :admins
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :categories, only: [:show]
  resources :products, only: %i[index show]
  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
    put 'remove_one/:product_id', to: 'carts#removeone', as: :remove_one
  end

  resources :transactions, only: [:new, :create]

  namespace :admin do
    root to: 'products#index'
    resources :products, only: %i[index new create edit update destroy]
    resources :categories, only: %i[index new create edit update destroy]
    resources :orders, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories

  has_many :orders
  has_many :users, through: :orders
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      @category_array = params.dig(:product, :category_ids)
      @category_array.each do |cat|
        @category = Category.find(cat)
        @product.categories << @category
      end
      flash[:notice] = 'product added'
      redirect_to admin_products_path
    else
      flash[:notice] = 'product cant be blank'
      render ' admin/products/new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      @product.product_categories.destroy_all
      @category_array = params.dig(:product, :category_ids)
      @category_array.each do |cat|
        @category = Category.find(cat)
        @product.categories << @category
      end
      flash[:notice] = 'product updated'
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.destroy(params[:id])
    flash[:notice] = 'product removed'
    redirect_to admin_products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: [:index]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :description, :text, :price, :decimal)
  end
end

app/helpers/admin/products_helper.rb
# frozen_string_literal: true

module Admin::ProductsHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1 class='jumbotron'>welcome to shopper</h1>

<div class='container'>
  <div class='row'>
    <p><%= render 'shared/product', collection: @products %></p>
  </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class='jumbotron'>
  <strong>Name:</strong>
  <%= @product.name.upcase %>
</h1>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>


<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p><%= link_to 'Add to cart', add_to_cart_path(@product), method: :put %></p>

<p><%= link_to 'back to product list', product_path%></p>

<%#= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>